### ISSUE TITLE
漏洞扫描怎么实现？

### ISSUE THREAD

**Issue by littleheary** [w-digital-scanner/w12scan#25]
请问怎么实现漏洞扫描？我看仓库中展示里有漏洞情况，我在本地搭建好的，找不到能做漏洞扫描的地方呀。

**Comment by boy-hack** [comment]
有内置漏洞库自动进行扫描，也有在线漏洞库https://github.com/boy-hack/airbug进行扫描，这都是自动的

**Comment by littleheary** [comment]
奇怪了，我添加资产扫描完了以后，并没有做漏洞扫描呀。
