### ISSUE TITLE
如何解决windows环境下python manage.py makemigrations出错问题

### ISSUE THREAD

**Issue by safebaseline** [w-digital-scanner/w12scan#28]
UnicodeDecodeError: 'gbk' codec can't decode byte 0x8f in position 91206: illega
l multibyte sequence
![image](https://user-images.githubusercontent.com/38883009/57903338-32916280-78a0-11e9-957b-22c9d2fe061b.png)

**Comment by supershero007** [comment]
@safebaseline 貌似这个问题我也遇到了，在文件 \server\settings.py 中找到底部，把原来的代码修改为：
`with open(os.path.join(BASE_DIR, "application", "frontend", "data", "new_wappalyzer.json"),encoding='utf-8') as f:
    WAPP_ICON = json.load(f)["apps"]`
就能解决了。
