### ISSUE TITLE
关于部署环境的问题

### ISSUE THREAD

**Issue by ppbibo** [w-digital-scanner/w12scan#29]
我在本地可以正常搭建这个系统框架，但是在vps是无法搭建成功的。Why？ 难道只支持本地搭建的吗？

**Comment by boy-hack** [comment]
先参考 https://x.hacking8.com/post-340.html

**Comment by chinatso** [comment]
1G1H如何配置
根据服务器配置修改docker-compose.yml参数，设置elasticsearch内存占用大小，默认设置是521M，如果你是1G内存可以设置为128M。

具体，在W12Scan跟目下，docker-compose.yml找到ES_JAVA_OPTS=-Xms512m -Xmx512m修改为ES_JAVA_OPTS=-Xms128m -Xmx128m,但是代价是在搜索和分析时可能会报内存不足的错误。所以内存还是越高越好。
