### ISSUE TITLE
部署docker错误

### ISSUE THREAD

**Issue by K-eleven** [w-digital-scanner/w12scan#30]
我用的centos7.5安装docker，安装上之后，无法运行docker-compose up -d命令，这个是版本的问题还是我安装的问题？？？？
第二次成功执行docker-compose up -d命令之后
卡在如下页面
![image](https://user-images.githubusercontent.com/48718006/58145094-837bcf00-7c83-11e9-9091-497e288aca5a.png)
![image](https://user-images.githubusercontent.com/48718006/58145120-955d7200-7c83-11e9-82b2-1472d2bbca8d.png)

**Comment by boy-hack** [comment]
还在下载中.
