### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by supershero007** [w-digital-scanner/w12scan#31]
win10本地部署，按照https://x.hacking8.com/post-342.html 进行初始化es表操作时出现如下错误：

`PUT http://127.0.0.1:9200/w12scan/_mapping/domains [status:400 request:0.016s]`

**Comment by supershero007** [comment]
@boy-hack

**Comment by boy-hack** [comment]
使用这个版本的elasticsearch试试
```
docker pull elasticsearch:5.6-alpine
```
