### ISSUE TITLE
在本机部署时出错  python3 manage.py runserver 0.0.0.0:8000

### ISSUE THREAD

**Issue by myxss** [w-digital-scanner/w12scan#33]
![image](https://user-images.githubusercontent.com/33475775/58847940-39e5a800-86b7-11e9-9295-0ea796bab121.png)

**Comment by boy-hack** [comment]
请贴出详细报错信息

**Comment by coffeehb** [comment]
默认没有在0.0.0.0上启动，导致docker拉起后，浏览器打不开页面，需要进入w12scan_web_1 手动run起来。
