### ISSUE TITLE
docker 启动 static文件 403 无权访问

### ISSUE THREAD

**Issue by ontheway0101** [w-digital-scanner/w12scan#34]
该项目根目录 static 文件在 docker 容器中默认权限为 700，python 无权访问 static，导致 css 等静态资源无法访问。

临时解决方案：

    docker exec -ti w12scan-master_web_1 bash    # 进入容器
    chmod -R 777 ./static/    # 修改 static 权限

**Comment by boy-hack** [comment]
我并没有复现你所说的。

**Comment by ontheway0101** [comment]
建议重新拉取项目和docker镜像

我的实验环境如下：

- OS：CentOS Linux release 7.4.1708
- docker：1.13.1

使用 README 中提供的方法启动容器，方法如下

    git clone https://github.com/boy-hack/w12scan
    cd w12scan
    docker-compose up -d

如果不能复现，那么该 issue 保留一种临时应对 css 等静态资源读取失败的解决方案
