### ISSUE TITLE
如何连接上reids数据库 需要映射？ 如下操作  密码为空或hellow12scan？

### ISSUE THREAD

**Issue by hack654a** [w-digital-scanner/w12scan#36]
![图片](https://user-images.githubusercontent.com/42664150/60064385-d63d2080-9732-11e9-8280-f9d17fad9daa.png)
![图片](https://user-images.githubusercontent.com/42664150/60064437-04bafb80-9733-11e9-87af-3f0a46fd777f.png)
![图片](https://user-images.githubusercontent.com/42664150/60064519-4186f280-9733-11e9-8ebb-f263c3bf5bad.png)
![图片](https://user-images.githubusercontent.com/42664150/60064564-67ac9280-9733-11e9-9a52-ddd3a7fe339d.png)
![图片](https://user-images.githubusercontent.com/42664150/60064620-99bdf480-9733-11e9-9e26-1f3d3038a220.png)
![图片](https://user-images.githubusercontent.com/42664150/60064705-d38efb00-9733-11e9-9fa2-0fe3532afb3a.png)
![图片](https://user-images.githubusercontent.com/42664150/60065476-89f3df80-9736-11e9-9b29-a0e3327e21eb.png)

**Comment by boy-hack** [comment]
查找redis所在docker的IP就能连了，应该是172开头的

**Comment by hack654a** [comment]
可能要做端口转发  172 均连不上  
![图片](https://user-images.githubusercontent.com/42664150/60086113-19b48080-976d-11e9-843b-3372db62b5ea.png)
![图片](https://user-images.githubusercontent.com/42664150/60086225-436da780-976d-11e9-90b4-adc6be614508.png)
![图片](https://user-images.githubusercontent.com/42664150/60086296-68621a80-976d-11e9-8589-a4146aff0820.png)
![图片](https://user-images.githubusercontent.com/42664150/60086395-95163200-976d-11e9-9366-6c56a3184255.png)
![图片](https://user-images.githubusercontent.com/42664150/60086480-b840e180-976d-11e9-9230-fae3c390f5e4.png)
![Uploading 图片.png…]()

**Comment by boy-hack** [comment]
密码是hellow12scan,肯定能连上的，不然docker之间如何通信？

**Comment by hack654a** [comment]
最后一张图    实验证明可以 
![图片](https://user-images.githubusercontent.com/42664150/60114003-82b7ea80-97a5-11e9-9e33-88b0e8264e4a.png)
![图片](https://user-images.githubusercontent.com/42664150/60114090-abd87b00-97a5-11e9-9067-455efeed1a08.png)
![图片](https://user-images.githubusercontent.com/42664150/60114270-17224d00-97a6-11e9-856a-a424a80ffb8b.png)
![图片](https://user-images.githubusercontent.com/42664150/60114422-61a3c980-97a6-11e9-977c-c9d43e76013a.png)
![图片](https://user-images.githubusercontent.com/42664150/60114516-8bf58700-97a6-11e9-98f6-a27b44d897f2.png)

![图片](https://user-images.githubusercontent.com/42664150/60114322-34571b80-97a6-11e9-89dd-95d91f535e25.png)
