### ISSUE TITLE
语言切换是不是没有开发好？

### ISSUE THREAD

**Issue by hack2012** [w-digital-scanner/w12scan#37]
昨天测试还是中文的，今天重新装了一下，就是英文了。
兄弟，能不能先服务好中国用户再考虑国外的？ 
先把bug处理处理再说嘛。。比如说资产ip过大的时候报错的bug

**Comment by boy-hack** [comment]
中英文可以切换的呀，点击🇨🇳图标就可以切换了，报错把报错的详细信息贴出来（多大数据，报错信息，报错截图，配置等等）不然无法定位错误

**Comment by boy-hack** [comment]
默认使用的es 是512内存，报错可能与它有关，调大点内存就行了https://github.com/w-digital-scanner/w12scan/blob/master/docker-compose.yml

**Comment by hack2012** [comment]
> 中英文可以切换的呀，点击🇨🇳图标就可以切换了，报错把报错的详细信息贴出来（多大数据，报错信息，报错截图，配置等等）不然无法定位错误

只是设置一个cookie值，不会报错的。给你一下截图。
![1](https://user-images.githubusercontent.com/3817100/60080480-9a21b400-9762-11e9-95cc-1f41fc6625e0.png)
![2](https://user-images.githubusercontent.com/3817100/60080481-9aba4a80-9762-11e9-9138-f94a98576acd.png)
![3](https://user-images.githubusercontent.com/3817100/60080482-9aba4a80-9762-11e9-8c0f-a7b4d93a53e5.png)
![4](https://user-images.githubusercontent.com/3817100/60080485-9b52e100-9762-11e9-8de9-d39897c65f73.png)

发现你今天多增加了个切换语言的功能，是不是没有测试好？

**Comment by hack2012** [comment]
> 默认使用的es 是512内存，报错可能与它有关，调大点内存就行了https://github.com/w-digital-scanner/w12scan/blob/master/docker-compose.yml

我调整为1024了，一会测试一下。

**Comment by boy-hack** [comment]
感谢提醒，语言切换确实有错误，已经更新了

**Comment by hack2012** [comment]
> 感谢提醒，语言切换确实有错误，已经更新了

没人解决兄弟

**Comment by hack2012** [comment]
方便加个微信或者QQ吗？

**Comment by boy-hack** [comment]
??还没解决吗，我这里是ok的，可以加telegram群聊

**Comment by hack2012** [comment]
> ??还没解决吗，我这里是ok的，可以加telegram群聊

我重装安装了好多次，最近直接在容器内改文件，搞定了。已经把bug修复了。
发起了pull requests，你合并一下吧，方便后来人。
