### ISSUE TITLE
如何对添加过的资产重新扫描，重新添加任务是不能实现，或者怎么删除已扫过的资产！

### ISSUE THREAD

**Issue by safebaseline** [w-digital-scanner/w12scan#42]

**Comment by safebaseline** [comment]
亟待解决

**Comment by boy-hack** [comment]
清空redis

**Comment by safebaseline** [comment]
有空能写个个手动启动的功能吗？



---原始邮件---
发件人: "boyhack"<notifications@github.com>
发送时间: 2019年8月15日(星期四) 上午10:09
收件人: "w-digital-scanner/w12scan"<w12scan@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"safebaseline"<798942836@qq.com>;
主题: Re: [w-digital-scanner/w12scan] 如何对添加过的资产重新扫描，重新添加任务是不能实现，或者怎么删除已扫过的资产！ (#42)



清空redis

**Comment by boy-hack** [comment]
> 有空能写个个手动启动的功能吗？
> […](#)
> ---原始邮件--- 发件人: "boyhack"<notifications@github.com> 发送时间: 2019年8月15日(星期四) 上午10:09 收件人: "w-digital-scanner/w12scan"<w12scan@noreply.github.com>; 抄送: "Author"<author@noreply.github.com>;"safebaseline"<798942836@qq.com>; 主题: Re: [w-digital-scanner/w12scan] 如何对添加过的资产重新扫描，重新添加任务是不能实现，或者怎么删除已扫过的资产！ (#42) 清空redis — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

设计思想就是扫描一个URL并缓存一段时间，缓存时间一过便可以再次扫描，不需要这个功能

**Comment by safebaseline** [comment]
大约是多少时间，会再次扫描

**Comment by safebaseline** [comment]
没有进行扫描任务，资产过多还是会出现这种问题
![图片](https://user-images.githubusercontent.com/38883009/63137659-c393e900-c009-11e9-8247-91b8f5ba9400.png)
****
![图片](https://user-images.githubusercontent.com/38883009/63137756-09e94800-c00a-11e9-91b8-7b99945f8c13.png)

**Comment by boy-hack** [comment]
> 没有进行扫描任务，资产过多还是会出现这种问题
> ![图片](https://user-images.githubusercontent.com/38883009/63137659-c393e900-c009-11e9-8247-91b8f5ba9400.png)
> 
> ![图片](https://user-images.githubusercontent.com/38883009/63137756-09e94800-c00a-11e9-91b8-7b99945f8c13.png)

和配置相关，elasticsearch需要至少4G内存，默认是2G，你要根据实际情况修改docker-compose的配置

**Comment by safebaseline** [comment]
![图片](https://user-images.githubusercontent.com/38883009/63146907-1f249d80-c02f-11e9-8a8e-192d49abeb89.png)
没有效果
