### ISSUE TITLE
添加多个目标，http连接就会报错

### ISSUE THREAD

**Issue by Yoga7xm** [w-digital-scanner/w12scan#44]
报错：
Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f702037e7f0>, 'Connection to timed out. (connect timeout=30)'))"
这不是因为http连接太多没有关闭导致的吗、

**Comment by boy-hack** [comment]
连接超时，不用管
