### ISSUE TITLE
在win10使用docker部署启动失败

### ISSUE THREAD

**Issue by liyunfei0302** [w-digital-scanner/w12scan#45]
我按照文档中描述的启动失败了
`λ docker-compose up -d
Building web
Step 1/10 : FROM alpine:edge
 ---> 70997d35b3ed
Step 2/10 : MAINTAINER w8ay@qq.com
 ---> Using cache
 ---> b19d99808266
Step 3/10 : RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
 ---> Using cache
 ---> 2c58dec142e6
Step 4/10 : RUN set -x     && apk update     && apk add python3-dev     && apk add bash     && apk add tzdata     && apk add gcc     && apk add gettext
     && apk add libc-dev     && apk add linux-headers     && apk add nginx     && cp -r -f /usr/share/zoneinfo/Hongkong /etc/localtime     && mkdir -p /opt/w12scan     && mkdir -p /run/nginx
 ---> Running in d567f0b1a838
+ apk update
fetch http://mirrors.ustc.edu.cn/alpine/edge/main/x86_64/APKINDEX.tar.gz
ERROR: http://mirrors.ustc.edu.cn/alpine/edge/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.a6975cf8.tar.gz: No such file or directory
fetch http://mirrors.ustc.edu.cn/alpine/edge/community/x86_64/APKINDEX.tar.gz
ERROR: http://mirrors.ustc.edu.cn/alpine/edge/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.c6765341.tar.gz: No such file or directory
2 errors; 14 distinct packages available
ERROR: Service 'web' failed to build: The command '/bin/sh -c set -x     && apk update     && apk add python3-dev     && apk add bash     && apk add tzdata     && apk add gcc     && apk add gettext     && apk add libc-dev     && apk add linux-headers     && apk add nginx     && cp -r -f /usr/share/zoneinfo/Hongkong /etc/localtime     && mkdir -p /opt/w12scan     && mkdir -p /run/nginx' returned a non-zero code: 2`

帮忙解决一下，谢谢啦

**Comment by boy-hack** [comment]
网络问题

**Comment by liyunfei0302** [comment]
是网络问题，设置了DNS服务器就好了
