### ISSUE TITLE
初始化es表失败

### ISSUE THREAD

**Issue by stuhk** [w-digital-scanner/w12scan#46]
想自己改下代码,再本地搭建了环境

到这一步的时候,失败了
![image](https://user-images.githubusercontent.com/11814078/63743768-e5298600-c8cf-11e9-87fb-a87ffb285d07.png)
![image](https://user-images.githubusercontent.com/11814078/63743827-0f7b4380-c8d0-11e9-90fb-e19e797c728c.png)
一直这样子
这是啥原因

**Comment by boy-hack** [comment]
es的版本是？

**Comment by stuhk** [comment]
> es的版本是？

7.3.0 windows版本的

**Comment by stuhk** [comment]
> es的版本是？

手动创建索引之后这样提示
![image](https://user-images.githubusercontent.com/11814078/63919333-20af8600-ca71-11e9-8630-959f0c1f0ceb.png)

**Comment by stuhk** [comment]
解决了

**Comment by stuhk** [comment]
版本问题
