### ISSUE TITLE
docker-compose pip3报错

### ISSUE THREAD

**Issue by he1dan** [w-digital-scanner/w12scan#61]
+ cp /opt/w12scan/dockerconf/w12scan_nginx.conf /etc/nginx/conf.d/w12scan_nginx.conf
+ pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -r /opt/w12scan/requirements.txt
/bin/sh: pip3: not found

centos7 pip3已经安装 可以正常使用。手动也可以安装

**Comment by bittrwf2** [comment]
Step 6/10 : RUN set -x     && cp /opt/w12scan/dockerconf/w12scan_nginx.conf /etc/nginx/conf.d/w12scan_nginx.conf     && pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -r /opt/w12scan/requirements.txt     && chmod a+x /opt/w12scan/dockerconf/start.sh     && apk del gcc     && apk del libc-dev     && apk del linux-headers     && rm -f /var/cache/apk/*
 ---> Running in 6a7e719f732c
+ cp /opt/w12scan/dockerconf/w12scan_nginx.conf /etc/nginx/conf.d/w12scan_nginx.conf
+ pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -r /opt/w12scan/requirements.txt
/bin/sh: pip3: not found
ERROR: Service 'web' failed to build: The command '/bin/sh -c set -x     && cp /opt/w12scan/dockerconf/w12scan_nginx.conf /etc/nginx/conf.d/w12scan_nginx.conf     && pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -r /opt/w12scan/requirements.txt     && chmod a+x /opt/w12scan/dockerconf/start.sh     && apk del gcc     && apk del libc-dev     && apk del linux-headers     && rm -f /var/cache/apk/*' returned a non-zero code: 127

**Comment by pokitpeng** [comment]
把Dockerfile文件中的 alpine:edge 换成 alpine:3.7 就可以了

**Comment by xiaoleng121** [comment]
> 把Dockerfile文件中的 alpine:edge 换成 alpine:3.7 就可以了

感谢解答  太及时了

**Comment by boy-hack** [comment]
@pokitpeng 感谢，已经更新了
