### ISSUE TITLE
设计架构图中三处拼写错误

### ISSUE THREAD

**Issue by starnightcyber** [w-digital-scanner/w12scan#62]
您好，看了下您的设计架构图，发现三处错别字，特告知：
```
service='http'
plugin='domain'
wappalyzer
```

![image](https://user-images.githubusercontent.com/19260696/75861189-fe3f6080-5e37-11ea-90ba-de9ac9bfcde6.png)

**Comment by hack2012** [comment]
兄弟够细心呀。

**Comment by starnightcyber** [comment]
> 兄弟够细心呀。

看图的时候，还是比较容易看出来的额(⊙o⊙)…
