### ISSUE TITLE
提示webfailed to build

### ISSUE THREAD

**Issue by aqa46698** [w-digital-scanner/w12scan#66]
老是提示找不到
![111](https://user-images.githubusercontent.com/51192822/79086408-80437300-7d6e-11ea-8c05-2185bb30ae36.png)
python包 但是已经安装了
![222](https://user-images.githubusercontent.com/51192822/79086459-ae28b780-7d6e-11ea-893d-2bc844a5b703.png)
不知道是什么原因 有没有好心人教一下

**Comment by boy-hack** [comment]
测试最新版已经可以了，再试试
